name: checks.scripts

on:
  push:
  pull_request:

jobs:
  icons-build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ macos, ubuntu, windows ]
      fail-fast: false # Still interested to see results from other combinations
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install ImageMagick on macOS
        if: matrix.os == 'macos'
        run: brew install imagemagick
      -
        name: Setup node
        uses: ./.github/actions/setup-node
      -
        name: Install dependencies
        uses: ./.github/actions/npm-install-dependencies
      -
        name: Create icons
        run: npm run icons:build

  install-deps:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        install-deps-before: [true, false]
        install-command:
          - npm run install-deps
          - npm run install-deps -- --no-errors
          - npm run install-deps -- --ci
          - npm run install-deps -- --fresh --non-deterministic
          - npm run install-deps -- --fresh
          - npm run install-deps -- --non-deterministic
        os: [ macos, ubuntu, windows ]
      fail-fast: false # Still interested to see results from other combinations
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup node
        uses: ./.github/actions/setup-node
      -
        name: Install dependencies
        if: matrix.install-deps-before == true
        uses: ./.github/actions/npm-install-dependencies
      -
        name: Run install-deps
        run: ${{ matrix.install-command }}

  configure-vscode:
    runs-on: ${{ matrix.os.name }}-latest
    strategy:
      matrix:
        os:
          - name: macos
            install-vscode-command: brew install --cask visual-studio-code
          - name: ubuntu
            install-vscode-command: sudo snap install code --classic
          - name: windows
            install-vscode-command: choco install vscode
      fail-fast: false # Still interested to see results from other combinations
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      -
        name: Install VSCode
        run: ${{ matrix.os.install-vscode-command }}
      -
        name: Configure VSCode
        run: python3 ./scripts/configure_vscode.py

  add_missing_ids:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ macos, ubuntu, windows ]
    steps:
      -
        name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      -
        name: Run the script
        run: python3 ./scripts/add_missing_ids.py
