name: Test

on: [ push, pull_request ]

jobs:
  run-tests:
    strategy:
      matrix:
        os: [macos, ubuntu, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      -
        name: Install dependencies
        run: npm ci
      -
        name: Run tests
        run: npm run test:unit
