name: Test

on:
  push:
  pull_request:
  schedule: # for integration tests
    - cron: '0 0 * * 0' # at 00:00 on every Sunday

jobs:
  run-tests:
    strategy:
      matrix:
        os: [macos, ubuntu, windows]
      fail-fast: false # So it still runs on other OSes if one of them fails
    runs-on: ${{ matrix.os }}-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      -
        name: Install dependencies
        run: npm ci
      -
        name: Run unit tests
        run: npm run test:unit
      -
        name: Run integration tests
        run: npm run test:integration
